# Generated by Django 5.0.4 on 2024-05-17 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sku', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('url', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('LastScrappeddate', models.DateTimeField(auto_now=True)),
                ('Updateddate', models.DateTimeField(auto_now=True)),
                ('Createddate', models.DateTimeField(auto_now_add=True)),
                ('Status', models.CharField(max_length=50)),
                ('main_image_url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_url', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'db_table': 'images',
            },
        ),
    ]
